import SidePanel from "@/components/left-sidebar"

export const metadata = {
    title: 'Test | top 3 | App',
    description: 'Generated by create next app',
  }

export default function TopUsers() {
    return (
      <main >
        <SidePanel />
        <span id="red">Мне лень было делать это :D</span> 
        <img src="https://media.tenor.com/P-8ZvqnS4AwAAAAC/dancing-cat-dancing-kitten.gif" className="small"/>
      </main>
    )
  }