import ProfilePages from "@/components/ProfilePages"
import WarningProfile from "@/components/Warning_Profilepage"
import SidePanel from "@/components/left-sidebar"

export const metadata = {
    title: 'Test | Profile | App',
    description: 'Generated by create next app',
  }

export default function ProfilePage() {
    return (
      <main >
        <SidePanel />
        <ProfilePages />
        <WarningProfile />
      </main>
    )
  }