import SidePanel from "@/components/left-sidebar"
import FruitInTop from "@/components/topFruit"

export const metadata = {
    title: 'Test | in top | App',
    description: 'Generated by create next app',
  }

export default function TopFruit() {
    return (
      <main >
        <SidePanel />
        <FruitInTop />
      </main>
    )
  }